In [ ]:
import pandas as pd
df = pd.DataFrame({
    'atributo1': [1,2,3],
    'atributo2': [5,6,7],
    'rotulo': ['alto', 'medio', 'baixo']
})
df

atributo1  atributo2 rotulo
0          1          5   alto
1          2          6  medio
2          3          7  baixo

In [ ]:
#df[['atributo1', 'atributo2']]
atributos = df.drop('rotulo', axis=1)
rotulo = df['rotulo']
atributos

atributo1  atributo2
0          1          5
1          2          6
2          3          7

In [ ]:
rotulo

0     alto
1    medio
2    baixo
Name: rotulo, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
help(LabelEncoder)

Help on class LabelEncoder in module sklearn.preprocessing._label:

class LabelEncoder(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  Encode target labels with value between 0 and n_classes-1.
 |  
 |  This transformer should be used to encode target values, *i.e.* `y`, and
 |  not the input `X`.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_targets>`.
 |  
 |  .. versionadded:: 0.12
 |  
 |  Attributes
 |  ----------
 |  classes_ : ndarray of shape (n_classes,)
 |      Holds the label for each class.
 |  
 |  See Also
 |  --------
 |  OrdinalEncoder : Encode categorical features using an ordinal encoding
 |      scheme.
 |  OneHotEncoder : Encode categorical features as a one-hot numeric array.
 |  
 |  Examples
 |  --------
 |  `LabelEncoder` can be used to normalize labels.
 |  
 |  >>> from sklearn import preprocessing
 |  >>> le = preprocessing.LabelEncoder()
 |  >>> le.fit([1, 2, 2, 6])
 |  LabelEncoder()
 |  >>> le.classes_
 |  array([1, 2, 6])
 |  >>

In [ ]:
codificador = LabelEncoder()
codificador

LabelEncoder()

In [ ]:
codificador.fit(rotulo) #treinamento

LabelEncoder()

In [ ]:
codificador.transform(rotulo)

array([0, 2, 1])

In [ ]:
rotulo

0     alto
1    medio
2    baixo
Name: rotulo, dtype: object

In [ ]:
codificador.classes_


array(['alto', 'baixo', 'medio'], dtype=object)

In [ ]:
codificador.inverse_transform([0,0,1,1,2,2])

array(['alto', 'alto', 'baixo', 'baixo', 'medio', 'medio'], dtype=object)

In [ ]:
df_pandas = pd.DataFrame({
    'atributo1': [1,2,3],
    'atributo2': [5,6,7],
    'rotulo': ['alto', 'medio', 'baixo']
})

mapa={
    'baixo': 0,
    'medio': 1,
    'alto': 2
}

df_pandas['rotulo_codificado'] = df_pandas['rotulo'].map(mapa)
df_pandas.drop('rotulo', axis=1)

atributo1  atributo2  rotulo_codificado
0          1          5                  2
1          2          6                  1
2          3          7                  0

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'atributo1': [1,2,3],
    'atributo2': [5,6,7],
    'rotulo': ['alto', 'medio', 'baixo']
})
df

atributo1  atributo2 rotulo
0          1          5   alto
1          2          6  medio
2          3          7  baixo

In [ ]:
from sklearn.preprocessing import LabelBinarizer
help(LabelBinarizer)

Help on class LabelBinarizer in module sklearn.preprocessing._label:

class LabelBinarizer(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  LabelBinarizer(*, neg_label=0, pos_label=1, sparse_output=False)
 |  
 |  Binarize labels in a one-vs-all fashion.
 |  
 |  Several regression and binary classification algorithms are
 |  available in scikit-learn. A simple way to extend these algorithms
 |  to the multi-class classification case is to use the so-called
 |  one-vs-all scheme.
 |  
 |  At learning time, this simply consists in learning one regressor
 |  or binary classifier per class. In doing so, one needs to convert
 |  multi-class labels to binary labels (belong or does not belong
 |  to the class). LabelBinarizer makes this process easy with the
 |  transform method.
 |  
 |  At prediction time, one assigns the class for which the corresponding
 |  model gave the greatest confidence. LabelBinarizer makes this easy
 |  with the inverse_transform method.
 |  
 |  Rea

In [ ]:
df

atributo1  atributo2 rotulo
0          1          5   alto
1          2          6  medio
2          3          7  baixo

In [ ]:
atributos = df.drop('rotulo', axis=1)
atributos

atributo1  atributo2
0          1          5
1          2          6
2          3          7

In [ ]:
rotulo = df['rotulo']
rotulo

0     alto
1    medio
2    baixo
Name: rotulo, dtype: object

In [ ]:
l_binarizer = LabelBinarizer()
l_binarizer

LabelBinarizer()

In [ ]:
l_binarizer.fit(rotulo)

LabelBinarizer()

In [ ]:
l_binarizer.classes_

array(['alto', 'baixo', 'medio'], dtype='<U5')

In [ ]:
l_binarizer.transform(rotulo)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [ ]:
import numpy as np
l_binarizer.inverse_transform(np.array([
    [0,0,1],
    [0,0,1],
    [0,1,0],
    [0,1,0],
    [1,0,0],
    [1,0,0],
]))

array(['medio', 'medio', 'baixo', 'baixo', 'alto', 'alto'], dtype='<U5')

In [ ]:
df_pandas = df.copy()
pd.get_dummies(df_pandas['rotulo'])

alto  baixo  medio
0     1      0      0
1     0      0      1
2     0      1      0