In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
lista = [1,2,3,4,5]
lista

[1, 2, 3, 4, 5]

In [ ]:
vetor = np.array(lista)
vetor

array([1, 2, 3, 4, 5])

In [ ]:
type(lista), type(vetor)

(list, numpy.ndarray)

In [ ]:
lista = list(range(1000000))
len(lista)

1000000

In [ ]:
vetor = np.array(lista)
vetor

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
len(vetor)

1000000

In [ ]:
vetor.shape

(1000000,)

In [ ]:
import sys
sys.getsizeof(lista)

8000056

In [ ]:
sys.getsizeof(vetor)

8000112

In [ ]:
s_lista = [[10, 6, 4, 8], [5,6,5,6]]
s_lista

[[10, 6, 4, 8], [5, 6, 5, 6]]

In [ ]:
s_vetor = np.array(s_lista)
s_vetor

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6]])

In [ ]:
s_lista[0][3]

8

In [ ]:
s_vetor[0,3] # semestre, prova

8

In [ ]:
s_vetor.dtype

dtype('int64')

In [ ]:
s_vetor.ndim

2

In [ ]:
s_vetor+1

array([[11,  7,  5,  9],
       [ 6,  7,  6,  7]])

In [ ]:
s_vetor-1
#s_vetor = s_vetor-1

array([[9, 5, 3, 7],
       [4, 5, 4, 5]])

In [ ]:
s_vetor*2

array([[20, 12,  8, 16],
       [10, 12, 10, 12]])

In [ ]:
(s_vetor/2).dtype

dtype('float64')

In [ ]:
10/2, 10%2

(5.0, 0)

In [ ]:
11//2, 11%2

(5, 1)

In [ ]:
s_vetor % 2

array([[0, 0, 0, 0],
       [1, 0, 1, 0]])

In [ ]:
resultado = []
for index in range(len(s_lista)): #0,1
   resultado.append([])
   for nota in s_lista[index]:
    resultado[index].append(nota % 2 == 0)

resultado

[[True, True, True, True], [False, True, False, True]]

In [ ]:
s_vetor % 3

array([[1, 0, 1, 2],
       [2, 0, 2, 0]])

In [ ]:
e_impar = s_vetor % 2 == 1
e_impar

array([[False, False, False, False],
       [ True, False,  True, False]])

In [ ]:
s_vetor[s_vetor % 2 == 1]

array([5, 5])

In [ ]:
resultado = []
for index in range(len(s_lista)): #0,1
  for nota in s_lista[index]:
    if nota % 2 == 1:
      resultado.append(nota)

resultado

[5, 5]

In [ ]:
resultado

[5, 5]

In [ ]:
s_vetor

array([[10,  6,  4,  8],
       [ 5,  6,  5,  6]])

In [ ]:
s_lista

[[10, 6, 4, 8], [5, 6, 5, 6]]

In [ ]:
a_lista = [
    s_lista,
    s_lista
]
a_lista

[[[10, 6, 4, 8], [5, 6, 5, 6]], [[10, 6, 4, 8], [5, 6, 5, 6]]]

In [ ]:
a_vetor = np.array(a_lista)
a_vetor

array([[[10,  6,  4,  8],
        [ 5,  6,  5,  6]],

       [[10,  6,  4,  8],
        [ 5,  6,  5,  6]]])

In [ ]:
#ano, semestre, prova => [ano, semestre, prova]
a_vetor[1, 1, -1]

6

In [ ]:
a_vetor[1, 1, 2:]

array([5, 6])

In [ ]:
a_vetor[1, :, 2:]

array([[4, 8],
       [5, 6]])

In [ ]:
a_vetor[:, :, -2:]

array([[[4, 8],
        [5, 6]],

       [[4, 8],
        [5, 6]]])

In [ ]:
a_vetor[:, :, [0, -1]]

array([[[10,  8],
        [ 5,  6]],

       [[10,  8],
        [ 5,  6]]])

In [ ]:
a_vetor[:, 0, 1:3]

array([[6, 4],
       [6, 4]])

In [ ]:
ano = [0,0,1]
semestre = [0,1,0]
prova = [0,2,-1]
a_vetor[ano, semestre, prova]

array([10,  5,  8])

In [ ]:
# criação

In [ ]:
#import numpy as np
np.zeros([2,2,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones([2,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full([2,2,4], 10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(16).reshape([2,2,4])
#16 => 2*2*4 = 16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
np.random.randint(0, 11, [2,2,4])

array([[[3, 9, 1, 4],
        [8, 9, 3, 1]],

       [[5, 9, 4, 5],
        [7, 3, 9, 0]]])

In [ ]:
np.random.rand(2,2,4)*100

array([[[26.5103938 , 78.9622285 ,  6.69380743, 73.02149421],
        [16.91356061, 12.08504615, 65.12568258, 38.74864521]],

       [[54.33026502, 95.69649371, 81.8390656 , 66.48163348],
        [97.85614392, 84.56034806, 63.42216444, 30.72449196]]])