In [ ]:
import pandas as pd
df = pd.DataFrame({
    'idade': [14,25,23,31,31,None,18,20,15,17,60]
})
df

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5     NaN
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
from sklearn.impute import SimpleImputer
help(SimpleImputer)

Help on class SimpleImputer in module sklearn.impute._base:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose='deprecated', copy=True, add_indicator=False, keep_empty_features=False)
 |  
 |  Univariate imputer for completing missing values with simple strategies.
 |  
 |  Replace missing values using a descriptive statistic (e.g. mean, median, or
 |  most frequent) along each column, or using a constant value.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan, None or pandas.NA, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_v

In [ ]:
constant_imputer = SimpleImputer(strategy='constant', fill_value=-1)
constant_imputer

SimpleImputer(fill_value=-1, strategy='constant')

In [ ]:
df

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5     NaN
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
array = df['idade'].to_numpy().reshape(-1,1)
array

array([[14.],
       [25.],
       [23.],
       [31.],
       [31.],
       [nan],
       [18.],
       [20.],
       [15.],
       [17.],
       [60.]])

In [ ]:
constant_imputer.fit(array) #treinamento

SimpleImputer(fill_value=-1, strategy='constant')

In [ ]:
df['constant'] = constant_imputer.transform(array)
df

idade  constant
0    14.0      14.0
1    25.0      25.0
2    23.0      23.0
3    31.0      31.0
4    31.0      31.0
5     NaN      -1.0
6    18.0      18.0
7    20.0      20.0
8    15.0      15.0
9    17.0      17.0
10   60.0      60.0

In [ ]:
df_pandas = pd.DataFrame({
    'idade': df['idade'].copy()
})
constant = -1
df_pandas[df_pandas.isnull()] = constant
df_pandas

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5    -1.0
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
mean_imputer = SimpleImputer(strategy='mean')
mean_imputer

SimpleImputer()

In [ ]:
mean_imputer.fit(array) #treinamento

SimpleImputer()

In [ ]:
mean_imputer.transform(array)

array([[14. ],
       [25. ],
       [23. ],
       [31. ],
       [31. ],
       [25.4],
       [18. ],
       [20. ],
       [15. ],
       [17. ],
       [60. ]])

In [ ]:
df['mean'] = mean_imputer.transform(array)
df

idade  constant  mean
0    14.0      14.0  14.0
1    25.0      25.0  25.0
2    23.0      23.0  23.0
3    31.0      31.0  31.0
4    31.0      31.0  31.0
5     NaN      -1.0  25.4
6    18.0      18.0  18.0
7    20.0      20.0  20.0
8    15.0      15.0  15.0
9    17.0      17.0  17.0
10   60.0      60.0  60.0

In [ ]:
df_pandas['idade'].mean()

23.0

In [ ]:
df_pandas = pd.DataFrame({
    'idade': df['idade'].copy()
})
media = df_pandas['idade'].mean()
df_pandas[df_pandas.isnull()] = media
df_pandas

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5    25.4
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
median_imputer = SimpleImputer(strategy='median')
median_imputer

SimpleImputer(strategy='median')

In [ ]:
median_imputer.fit(array) #treinamento

SimpleImputer(strategy='median')

In [ ]:
median_imputer.transform(array)

array([[14. ],
       [25. ],
       [23. ],
       [31. ],
       [31. ],
       [21.5],
       [18. ],
       [20. ],
       [15. ],
       [17. ],
       [60. ]])

In [ ]:
df['median'] = median_imputer.transform(array)
df

idade  constant  mean  median
0    14.0      14.0  14.0    14.0
1    25.0      25.0  25.0    25.0
2    23.0      23.0  23.0    23.0
3    31.0      31.0  31.0    31.0
4    31.0      31.0  31.0    31.0
5     NaN      -1.0  25.4    21.5
6    18.0      18.0  18.0    18.0
7    20.0      20.0  20.0    20.0
8    15.0      15.0  15.0    15.0
9    17.0      17.0  17.0    17.0
10   60.0      60.0  60.0    60.0

In [ ]:
df_pandas = pd.DataFrame({
    'idade': df['idade'].copy()
})
mediana = df_pandas['idade'].median()
df_pandas[df_pandas.isnull()] = mediana
df_pandas

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5    21.5
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
mode_imputer = SimpleImputer(strategy='most_frequent')
mode_imputer

SimpleImputer(strategy='most_frequent')

In [ ]:
mode_imputer.fit(array) #treinamento

SimpleImputer(strategy='most_frequent')

In [ ]:
mode_imputer.transform(array)

array([[14.],
       [25.],
       [23.],
       [31.],
       [31.],
       [31.],
       [18.],
       [20.],
       [15.],
       [17.],
       [60.]])

In [ ]:
array

array([[14.],
       [25.],
       [23.],
       [31.],
       [31.],
       [nan],
       [18.],
       [20.],
       [15.],
       [17.],
       [60.]])

In [ ]:
df['mode'] = mode_imputer.transform(array)
df

idade  constant  mean  median  mode
0    14.0      14.0  14.0    14.0  14.0
1    25.0      25.0  25.0    25.0  25.0
2    23.0      23.0  23.0    23.0  23.0
3    31.0      31.0  31.0    31.0  31.0
4    31.0      31.0  31.0    31.0  31.0
5     NaN      -1.0  25.4    21.5  31.0
6    18.0      18.0  18.0    18.0  18.0
7    20.0      20.0  20.0    20.0  20.0
8    15.0      15.0  15.0    15.0  15.0
9    17.0      17.0  17.0    17.0  17.0
10   60.0      60.0  60.0    60.0  60.0

In [ ]:
df_pandas = pd.DataFrame({
    'idade': df['idade'].copy()
})
mode = df_pandas['idade'].mode(0)
df_pandas[df_pandas.isnull()] = constant
df_pandas

idade
0    14.0
1    25.0
2    23.0
3    31.0
4    31.0
5    -1.0
6    18.0
7    20.0
8    15.0
9    17.0
10   60.0

In [ ]:
mode[0]

31.0