# Engenharia Software

```
Engenharia de software -> dados + logica => resultado
Machine learning -> dados + resultado => logica
```

In [ ]:
import numpy as np
np.random.seed(10)
dados = np.random.randint(1,91, 100)
dados

array([10, 16, 65, 29, 90, 30,  9, 74,  1, 41, 37, 17, 12, 55, 89, 63, 34,
       73, 79, 50, 52, 55, 78, 70, 14, 26, 14, 87, 31, 31, 90, 13, 66, 32,
       58, 37, 28, 19, 78, 23, 24, 12, 29, 75, 89, 10, 16, 19, 81, 72, 89,
       12, 18, 47,  8, 76, 29, 34, 85, 89, 45,  6,  5, 72, 89, 89, 51, 55,
       35, 16, 78, 89, 16,  7, 86, 23, 12, 13, 63, 58, 80, 43, 58, 51, 46,
       41, 90, 74, 38,  1, 19, 24,  4, 30, 17, 85, 83, 15, 52, 80])

In [ ]:
dados[dados == 19]

array([19, 19, 19])

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'idade': dados
})
df.head(6)

idade
0     10
1     16
2     65
3     29
4     90
5     30

In [ ]:
def e_adulto(idade):
  if idade > 18:
    return 'Adulto'
  else:
    return 'Criança'


In [ ]:
e_adulto(40)

'Adulto'

In [ ]:
e_adulto(7)

'Criança'

In [ ]:
df['resultado'] = df['idade'].apply(e_adulto)
df.head(6)

idade resultado
0     10   Criança
1     16   Criança
2     65    Adulto
3     29    Adulto
4     90    Adulto
5     30    Adulto

In [ ]:
mask_adulto = df['idade'] > 18
mask_adulto.head(6)

0    False
1    False
2     True
3     True
4     True
5     True
Name: idade, dtype: bool

In [ ]:
#df['mask_adulto', 'resultado'] = 'Adulto'
#df[~mask_adulto, 'resultado'] = 'Criança'

# Machine Learning

In [ ]:
df.head(6)

idade resultado (mask_adulto, resultado)
0     10   Criança                   Adulto
1     16   Criança                   Adulto
2     65    Adulto                   Adulto
3     29    Adulto                   Adulto
4     90    Adulto                   Adulto
5     30    Adulto                   Adulto

In [ ]:
from sklearn.tree import DecisionTreeClassifier, export_text
modelo = DecisionTreeClassifier()
modelo

DecisionTreeClassifier()

In [ ]:
dados = df['idade'].to_numpy().reshape(-1, 1)
resultado = df['resultado'].to_numpy().reshape(-1, 1)
dados

array([[10],
       [16],
       [65],
       [29],
       [90],
       [30],
       [ 9],
       [74],
       [ 1],
       [41],
       [37],
       [17],
       [12],
       [55],
       [89],
       [63],
       [34],
       [73],
       [79],
       [50],
       [52],
       [55],
       [78],
       [70],
       [14],
       [26],
       [14],
       [87],
       [31],
       [31],
       [90],
       [13],
       [66],
       [32],
       [58],
       [37],
       [28],
       [19],
       [78],
       [23],
       [24],
       [12],
       [29],
       [75],
       [89],
       [10],
       [16],
       [19],
       [81],
       [72],
       [89],
       [12],
       [18],
       [47],
       [ 8],
       [76],
       [29],
       [34],
       [85],
       [89],
       [45],
       [ 6],
       [ 5],
       [72],
       [89],
       [89],
       [51],
       [55],
       [35],
       [16],
       [78],
       [89],
       [16],
       [ 7],
       [86],
       [23],
       [12],

In [ ]:
resultado

array([['Criança'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],
       ['Criança'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Adulto'],
       ['Criança'],

In [ ]:
modelo.fit(dados, resultado) #treinamento

DecisionTreeClassifier()

In [ ]:
help(export_text)

Help on function export_text in module sklearn.tree._export:

export_text(decision_tree, *, feature_names=None, max_depth=10, spacing=3, decimals=2, show_weights=False)
    Build a text report showing the rules of a decision tree.
    
    Note that backwards compatibility may not be supported.
    
    Parameters
    ----------
    decision_tree : object
        The decision tree estimator to be exported.
        It can be an instance of
        DecisionTreeClassifier or DecisionTreeRegressor.
    
    feature_names : list of str, default=None
        A list of length n_features containing the feature names.
        If None generic names will be used ("feature_0", "feature_1", ...).
    
    max_depth : int, default=10
        Only the first max_depth levels of the tree are exported.
        Truncated branches will be marked with "...".
    
    spacing : int, default=3
        Number of spaces between edges. The higher it is, the wider the result.
    
    decimals : int, default=2
 

In [ ]:
print(export_text(modelo, feature_names=['idade']))

|--- idade <= 18.50
|   |--- class: Criança
|--- idade >  18.50
|   |--- class: Adulto

