# Questão 1

In [ ]:
#!pip install numpy
import numpy as np
matriz_1 = np.zeros([6,6])
matriz_2 = np.ones([4,4])
matriz_3 = np.full([2,2], 2)
matriz_3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


array([[2, 2],
       [2, 2]])

In [ ]:
matriz_1[1:-1,1:-1] = matriz_2
matriz_1[2:-2, 2:-2] = matriz_3
matriz_1

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.random.seed(0)
matriz_4 = np.random.randint(0, 3, [6,6])
matriz_1 - matriz_4

array([[ 0., -1.,  0., -1., -1., -2.],
       [ 0., -1.,  1.,  1.,  1., -2.],
       [-1., -1.,  0.,  2.,  0., -1.],
       [-1.,  0.,  2.,  1.,  1.,  0.],
       [-1., -1.,  1., -1.,  1., -1.],
       [-1., -2.,  0., -1., -1., -1.]])

# Questão 2

In [ ]:
matriz = np.arange(81).reshape([9,9])
impar = matriz%2 == 1
par = matriz%2 == 0
mult_7 = matriz % 7 == 0
matriz.diagonal()
linhas = [3,3,4,4]
colunas = [5,6,6,7]
matriz[linhas, colunas]

array([32, 33, 42, 43])

# Questão 3

In [ ]:
[0,0,0]
[3,2,0]
[3,2,-1]
[4,0,0]
[8,0,-1]
[9,1,4]
[10,0,1]
[11,-1,3]

In [ ]:
mes_lista = list(range(1,29))
ano_lista = list(range(1,29)) * 12
matriz_ano = np.array(ano_lista).reshape(12,4,7) #mes, semana, dia
matriz_ano = matriz_ano.astype(str)
matriz_ano[:,:,:] = 'D'
matriz_ano[:,:, -2:] = 'W'
#comeco_mes = matriz_ano == '1'#maskara
#matriz_ano[comeco_mes] = 'S'
matriz_ano[:,0,0] = 'S'
matriz_ano[:,-1,-1] = 'E'
meses = [0,3,3,4,8,9,10,10,11]
semanas = [0,2,2,0,0,1,0,2,-1]
dias = [0,0,-1,0,-1,4,1,-1,3]
matriz_ano[meses, semanas, dias]
matriz_ano

array([[['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'E']],

       [['S', 'D', 'D', 'D', 'D', 'W', 'W'],
        ['D', 'D', 'D', 'D', 'D', 'W', 'W'],
